//
// Generated file, do not edit! Created by nedtool 5.6 from SatMsg.msg.
//

#ifndef __SATMSG_M_H
#define __SATMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>SatMsg.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet SatMsg
 * {
 *     string source;
 *     string destination;
 * 
 *     int hopCount = 0;
 * }
 * </pre>
 */
class SatMsg : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string source;
    ::omnetpp::opp_string destination;
    int hopCount;

  private:
    void copy(const SatMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SatMsg&);

  public:
    SatMsg(const char *name=nullptr, short kind=0);
    SatMsg(const SatMsg& other);
    virtual ~SatMsg();
    SatMsg& operator=(const SatMsg& other);
    virtual SatMsg *dup() const override {return new SatMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSource() const;
    virtual void setSource(const char * source);
    virtual const char * getDestination() const;
    virtual void setDestination(const char * destination);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const SatMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, SatMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __SATMSG_M_H

